name: 'CI checks'
on: ['push', 'pull_request']
jobs:
  coding-style:
    runs-on: 'ubuntu-latest'
    name: 'Check coding style'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: Install elastic-package binary
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific tag
          repo: elastic/elastic-package
          tag: v0.85.0
      - name: Lint package
        run: elastic-package check -v

  install-check:
    runs-on: 'ubuntu-latest'
    name: 'Check installation'
    steps:     
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: Install elastic-package binary
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific tag
          repo: elastic/elastic-package
          tag: v0.85.0

      - name: Setup stack
        run: |
          eval "$(elastic-package stack shellinit)"
          elastic-package stack up -d -v
      - name: Run install
        run: |-
          eval "$(elastic-package stack shellinit)"
          elastic-package install -v
