name: 'CI checks'
on: ['push', 'pull_request']
jobs:
  cs:
    runs-on: 'ubuntu-latest'
    name: 'Coding style'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Install elastic-package
        run: go install github.com/elastic/elastic-package@latest

      - name: Lint package
        run: elastic-package lint
